[tool.black]
target-version= ['py36', 'py37', 'py38']
line-length=89
experimental_string_processing=true
include = '\.pyi?$'
exclude = '''
/(
	\.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/

[tool.isort]
profile='black'
multi_line_output=3
